#ifndef WB_DEFAULTS_H_
#define WB_DEFAULTS_H_

#define WB_DEFAULT_BACKGROUND_CENTER_COLOUR 0xFFFFFF
#define WB_DEFAULT_BACKGROUND_EDGE_COLOUR 0xF1F2F4

#define WB_DEFAULT_PATCH_OPACITY 1.0f
#define WB_DEFAULT_PATCH_BLUR_RADIUS 0.0f
#define WB_DEFAULT_PATCH_GLOW_RADIUS 0.0f
#define WB_DEFAULT_PATCH_GLOW_OPACITY 0.35f
#define WB_MAX_PATCH_BLUR_RADIUS 32.0f
#define WB_DEFAULT_PATCH_JITTER_STRENGTH 0.0f
#define WB_AUTO_PATCH_MOVE_JITTER_STRENGTH 1.0f
#define WB_AUTO_CAMERA_MOVE_JITTER_STRENGTH 0.7f
#define WB_MIN_JITTER_STRENGTH 0.0f
#define WB_DEFAULT_PATCH_CAMERA_DISTANCE 5.0f
#define WB_MIN_PATCH_CAMERA_DISTANCE 0.1f
#define WB_DEFAULT_PATCH_CAMERA_SCALE 260.0f
#define WB_MIN_PATCH_CAMERA_SCALE 1.0f
#define WB_DEFAULT_PATCH_CAMERA_YAW 0.0f
#define WB_DEFAULT_PATCH_CAMERA_PROJECTION 1
#define WB_DEFAULT_PATCH_CAMERA_CENTER_X (WIDTH * 0.5f)
#define WB_DEFAULT_PATCH_CAMERA_CENTER_Y (HEIGHT * 0.5f)
#define WB_DEFAULT_PATCH_OFFSET_X 0.0f
#define WB_DEFAULT_PATCH_OFFSET_Y 0.0f

#define WB_DEFAULT_OBJECT_JITTER_STRENGTH 0.0f
#define WB_AUTO_OBJECT_MOVE_JITTER_STRENGTH 1.1f
#define WB_DEFAULT_MATH_SIZE 0.13f
#define WB_DEFAULT_MATH_THICKNESS 1.0f

#define WB_MIN_OPACITY 0.0f
#define WB_MAX_OPACITY 1.0f

#define WB_DEFAULT_LINE_THICKNESS 0.0056f
#define WB_DEFAULT_OPEN_POINT_THICKNESS 0.0046f
#define WB_DEFAULT_POINT_RADIUS 0.0111f
#define WB_DEFAULT_OPEN_POINT_RADIUS 0.0148f
#define WB_DEFAULT_CIRCLE_RADIUS 0.0741f
#define WB_DEFAULT_ELLIPSE_RADIUS_X 0.1111f
#define WB_DEFAULT_ELLIPSE_RADIUS_Y 0.0741f
#define WB_DEFAULT_SHADE_OPACITY 0.25f
#define WB_DEFAULT_ARROW_HEAD_SIZE 0.0444f
#define WB_DEFAULT_DOTTED_GAP 0.0333f
#define WB_DEFAULT_DASHED_GAP 0.0333f

#endif
