#ifndef WB_DEFAULTS_H_
#define WB_DEFAULTS_H_

#define WB_DEFAULT_BACKGROUND_CENTER_COLOUR 0xFFFFFF
#define WB_DEFAULT_BACKGROUND_EDGE_COLOUR 0xF1F2F4

#define WB_DEFAULT_LAYER_OPACITY 1.0f
#define WB_DEFAULT_LAYER_BLUR_RADIUS 0.0f
#define WB_DEFAULT_LAYER_GLOW_RADIUS 0.0f
#define WB_DEFAULT_LAYER_GLOW_OPACITY 0.35f
#define WB_MAX_LAYER_BLUR_RADIUS 32.0f
#define WB_DEFAULT_LAYER_JITTER_STRENGTH 0.0f
#define WB_AUTO_LAYER_MOVE_JITTER_STRENGTH 1.0f
#define WB_AUTO_CAMERA_MOVE_JITTER_STRENGTH 0.7f
#define WB_MIN_JITTER_STRENGTH 0.0f
#define WB_DEFAULT_LAYER_CAMERA_DISTANCE 5.0f
#define WB_MIN_LAYER_CAMERA_DISTANCE 0.1f
#define WB_DEFAULT_LAYER_CAMERA_SCALE 260.0f
#define WB_MIN_LAYER_CAMERA_SCALE 1.0f
#define WB_DEFAULT_LAYER_CAMERA_YAW 0.0f
#define WB_DEFAULT_LAYER_CAMERA_PROJECTION 1
#define WB_DEFAULT_LAYER_CAMERA_CENTER_X (WIDTH * 0.5f)
#define WB_DEFAULT_LAYER_CAMERA_CENTER_Y (HEIGHT * 0.5f)
#define WB_DEFAULT_LAYER_OFFSET_X 0.0f
#define WB_DEFAULT_LAYER_OFFSET_Y 0.0f

#define WB_DEFAULT_OBJECT_JITTER_STRENGTH 0.0f
#define WB_AUTO_OBJECT_MOVE_JITTER_STRENGTH 1.1f
#define WB_DEFAULT_MATH_SIZE 70.0f
#define WB_DEFAULT_MATH_THICKNESS 1.0f

#define WB_MIN_OPACITY 0.0f
#define WB_MAX_OPACITY 1.0f

#define WB_DEFAULT_LINE_THICKNESS 3.0f
#define WB_DEFAULT_OPEN_POINT_THICKNESS 2.5f
#define WB_DEFAULT_POINT_RADIUS 6.0f
#define WB_DEFAULT_OPEN_POINT_RADIUS 8.0f
#define WB_DEFAULT_CIRCLE_RADIUS 40.0f
#define WB_DEFAULT_ELLIPSE_RADIUS_X 60.0f
#define WB_DEFAULT_ELLIPSE_RADIUS_Y 40.0f
#define WB_DEFAULT_SHADE_OPACITY 0.25f
#define WB_DEFAULT_ARROW_HEAD_SIZE 24.0f
#define WB_DEFAULT_DOTTED_GAP 18.0f
#define WB_DEFAULT_DASHED_GAP 18.0f

#endif
